name: Ok to preview

on:
  pull_request:
    types: [labeled]

jobs:
  ok-to-preview:
    runs-on: ubuntu-latest
    steps:

    - name: Debug
      id: debug
      uses: hmarr/debug-action@master
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'
    - run: |
        readarray -t removed_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.removed }}')"
        for removed_file in ${removed_files[@]}; do
          echo "Do something with this ${removed_file}."
        done
