name: Ok to preview

on:
  pull_request:
    types: [labeled]

jobs:
  ok-to-preview:
    runs-on: ubuntu-latest
    steps:

    # - name: Debug
    #   id: debug
    #   uses: hmarr/debug-action@master
    #   with:
    #     app_id: ${{ secrets.APP_ID }}
    #     private_key: ${{ secrets.PRIVATE_KEY }}

    - uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # - id: files
    #   uses: jitterbit/get-changed-files@v1
    #   with:
    #     format: 'json'

    - name: Get list of links
      id: links_list
      run: |
        # -*- coding: utf-8 -*-
        import os, json, textwrap

        all_files_path = os.path.join(os.environ["HOME"], "files.json")
        event_json_path = os.environ["GITHUB_EVENT_PATH"]

        with open(all_files_path) as f:
            all_files = json.load(f)

        with open(event_json_path) as f:
            event_data = json.load(f)

        links = [
          "https://strawberry.rocks/docs/pr/{pr_number}/{path}".format(
            pr_number=event_data["number"],
            path=file.replace(".md", "")
          )
          for file in all_files
          if file.startswith("docs/") and file.endswith(".md")
        ]

        links = json.dumps(links)
        output = "::set-output name=links::{}".format(links)

        print(output)
      shell: python

    # - name: Add comment to PR
    #   uses: unsplash/comment-on-pr@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     msg: ${{ steps.comment.outputs.message }}
    #     check_for_duplicate_msg: true

    - uses: actions/github-script@v1
      id: add-comment
      env:
        number: ${{ github.event.number }}
        links: ${{ steps.links_list.outputs.links }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const links = JSON.parse(process.env.links).join('\n')
          const message = `
            Hi 👋 You can find a preview of the docs here: \n${links}
          `.trim()
          await github.issues.createComment({
            issue_number: process.env.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          })
